# Generated by Django 2.1.7 on 2019-02-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0004_auto_20190222_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='confirm_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
