# Generated by Django 2.1.7 on 2019-03-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0005_auto_20190228_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='confirm_password',
        ),
    ]
