# Generated by Django 2.1.7 on 2019-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0007_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='is_archived',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
