# Generated by Django 2.1.7 on 2019-03-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0008_auto_20190325_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='filepath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
