# Generated by Django 2.1.7 on 2019-03-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0009_filepath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepath',
            old_name='filepath',
            new_name='filename',
        ),
    ]
